version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/deploy"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    # All packages here are for build only
    directory: "/dispenser_app"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "production"
