---
license: MIT-0
copyright: Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
chapter: false
pre: 
next: 
prev: 
title: 7. Review Cloud Architecture
weight: 70
---

== Objectives

This lab module will walk through how the dispenser, webapp, and coupled services interact. It will go into level of detail specific for the workshop. If you would like to review more details, please reference the link:/presenter.html[Setting Up the Workshop] documentation for deeper insights. By then end of this module you will have:

* An understanding of the relationship between the dispenser (_thing_), your Cognito user, and the DynamoDB database tables that track and log dispenser activity and state.
* Seen how the dispenser _thing_ uses the https://docs.aws.amazon.com/iot/latest/developerguide/iot-device-shadows.html[Device Shadow Service for AWS IoT] to listen for requested state changes, and also uses it for processing a dispense _request_ and acknowledging a _dispense_ response.
* Tested a _dispense_ request/response operation and monitored what takes place in different scenarios.
* Reviewed dispenser activity from both the DynamoDB _EventsTable_ and also webapp logging.
* An understanding of how the webapp along with the API Lambda functions control how to give credits to others, as well as only initiating a dispense event when there sufficient credits.

== Steps to Complete

Follow each step in order and use the *Open for detailed step-by-step instructions* if required.

=== Understand the AWS IoT Thing, Cognito User, and DynamoDB Table Relationships

As a software-as-a-service (SaaS) environment, there needs to be a specific relationship between all of the resources to help enforce the security and operational controls of the actions. At a high level, for each user, this is how the resources are associated with each other:

TODO: puml of thing - cert      - cog user - ddb tables
                      to policy

Each thing has a unique X.509 client certificate for authentication allowing the dispenser to connect publish and subscribe to the MQTT topics specific for that dispenser. This authorization of MQTT topics comes from a common policy that uses substitution variables that read the _Common Name_ value (which is the dispenser Id). The relationship continues into a Cognito User attribute, `custom:dispenserId`, that is read for every API call. Finally, your dispenser has an entry in the DynamoDB _DispenserTable_ that tracks current the credit balance and also any in-flight or stale command operations.

From the webapp, open the _MY DETAILS_ section and open a new browser tab or window to the Sign-in URL, then login in with the credentials provided. From the AWS Console, review the relationships by view your dispenser and user details in the following AWS services:

* *AWS IoT Core* - View your thing, the attached certificate details, and the policy associated with the certificate. Also, view the other security policy that is associated with your Cognito user (used to monitor update events).
* *Amazon Cognito* - From _Manage User Pools_, select the _workshop-users_, Users and Groups, then your select your username. Note the `custom:user` and `custom:dispenserId` attribute values.
* *Amazon DynamoDB* - From the _DispenserTable_ review the credits value for your dispenser via the _dispenserId_ sort key. From the _DispenserEvents_ table, query with the partition key equal to your dispenserId. As others start to create and operate their dispensers, filtering will limit to just your events.

{{%expand "Open for detailed step-by-step instructions" %}}

. From the webapp, open the _MY DETAILS_ section and open a new browser tab or window to the Sign-in URL, then login in with the credentials provided (username the same as the webapp, and use the generated password).
. Click on the _Services_ menu dropdown (upper left next to AWS logo), and type in _iot core_, then click on _IoT Core_ when the drop-down populates. This will direct you the the AWS IoT Core service page.
+
TIP: During the workshop you will be changing from service to service quite often. When navigating to a different service via the _Service->SERVICENAME_, right-click on the service name and select "Open in a new tab" (or equivalent). This will have all the services referenced within a single browser window on separate tabs.
+ . Click on _Get Started_ to take you to the main page, then select _Manage_ from the left tab. Click on _Skip tour_. Now from the 



{{% /expand%}}

=== Monitor Shadow changes for a simple operation (change LED status)


{{%expand "Open for detailed step-by-step instructions" %}}

detailed steps with markdown.
{{% /expand%}}

=== Monitor Shadow  MQTT topics for a dispense operation


{{%expand "Open for detailed step-by-step instructions" %}}

detailed steps with markdown.
{{% /expand%}}

=== View dynamoDB for logging events and change in credits


{{%expand "Open for detailed step-by-step instructions" %}}

detailed steps with markdown.
{{% /expand%}}

=== Webapp overviewe

uses cognito to auth for both API and MQTT connections. No polling, uses MQTT events to trigger making changes.

{{%expand "Open for detailed step-by-step instructions" %}}

detailed steps with markdown.
{{% /expand%}}


== Checkpoints

Please ensure the following checkpoints are validated before moving on to the next module.

## (optional) Outcomes

Lead off with something like "so why did we do x, y, and z?