---
license: MIT-0
copyright: Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
chapter: false
pre: <i class="fas fa-greater-than"></i>&nbsp;
next: 
prev: 
title: Message Flows
weight: 10
---

:source-highlighter: pygments
:pygments-style: monokai
:icons: font
:nocopyblocks:

== Device and Application Message Flows ==

The shadow document for devices tracks state of local resources. In the case of the motor board, this is `led` which maps to the _second_ motor controller, which is not used. This give an indicator that things are working without having to activate the motor.

The `led_ring` is the round ring and `count` determine how many LED elements to light up, and the color is the RBG color for all active elements. Each of these below will always be in the _desired_ state of the shadow and once online, in the _reported_ state for the device.

```json
{
    "led_ring": {
        "count": 0,
        "color": "#RRGGBB"
    },
    "led": "on|off",
    "dispense_time_ms": 2500,
}
```

There are also a temporary *request* and *response* objects used to track command state. The cloud logic will create the *request* object in the _desired_ state section of the shadow, and once processed by the device, it will create the *response* object in the _reported_ state section. Finally, cloud logic will reconcile and clean up the shadow document of any entries left.

Below are what the *request* and *response* objects should look like. The `command` and `requestId` attribute and values must match. For the *request* object, the `timestamp` attribute is when the request was made, while in the *response* object it is when the dispenser completed the operation.

```json
{
    "desired": {
        "request": {
            "command": "dispense",
            "requestId": "1234-5678",
            "timestamp": 12345
        }
    },
    "reported": {
        "response": {
            "command": "dispense",
            "requestId": "1234-5678",
            "result": "success",
            "timestamp": 45678
        }
    },
}
```

The following sequence diagrams show the flows for different uses. The first flows are device-to-cloud, then Rules Engine actions, and then API generated flows.

=== Device Flows

==== Turn on/off LED

Uses the device shadow to set the desired state of an LED. The unused motor controller's associated LED can be set `on` or `off`, while the LED ring can be addressed with an RGB color and number of LEDs to light. All LED operations take place through the device shadow.

At creation, the LEDs are all set to a _desired_ state of off. The dispenser hardware should read and honor the shadow settings for the LED.

.Turn on the LED
[plantuml, Turn on the LED, svg]
....
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v4.0/dist
!includeurl AWSPuml/AWSCommon.puml

!includeurl AWSPuml/InternetOfThings/IoTGeneric.puml
!includeurl AWSPuml/InternetOfThings/IoTCore.puml
!includeurl AWSPuml/InternetOfThings/IoTRule.puml
!includeurl AWSPuml/Mobile/APIGateway.puml
!includeurl AWSPuml/General/User.puml
!includeurl AWSPuml/SecurityIdentityAndCompliance/Cognito.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/Database/DynamoDB.puml

IoTGenericParticipant(dispenser, Dispenser, Id: 123) order 5
IoTCoreParticipant(broker, Message Broker,) order 10
IoTRuleParticipant(rule, Rules Engine,) order 30
LambdaParticipant(app, Dispenser App,) order 40
LambdaParticipant(logging, Log Events,) order 50

dispenser -> broker: S: 123/shadow/delta
app -> broker: P: 123/shadow/update {"desired": {"led": "on"}}
broker -> rule: shadow document
rule -> logging: event: shadow document

alt change between desired and reported
    broker -> dispenser: 123/shadow/delta {"led": "on"}
    dispenser -> dispenser: enable LED1
    dispenser -> broker: P: 123/shadow/update {"reported": {"led": "on"}}
    broker -> rule: shadow document
    rule -> logging: event: shadow document
end
....

In this flow:

. Dispenser subscribes to shadow delta topic, e.g., `$aws/things/123/shadow/delta`
. Dispenser publishes desired state change to shadow update for `led` (LED for second motor controller)
. _If_ there is a difference between _desired_ and _reported_ states, the delta, `"led": "on"` is sent to the dispenser
. Dispenser enables the LED locally
. Dispenser then publishes teh _reported_ state of LED1 to the shadow update topic
. Rules engine matches update operation and invokes logging event action

This is the same flow for `led1` and `led_ring`. For `led_ring`, the attributes are the amount of LEDs to light (0-5) and the RBG color in hex, e.g., `#ff0000` for full red.

[NOTE]
====
The LED operation can be `on` or `off`.
====

==== Activate Dispenser

Uses the device's shadow _desired_ state to send a command (request) to the dispenser. After the dispenser has completed the operation, it updates the shadow's _reported_ state to  acknowledge the request.

.Activate Dispenser
[plantuml, Activate Dispenser, svg]
....
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v4.0/dist
!includeurl AWSPuml/AWSCommon.puml

!includeurl AWSPuml/InternetOfThings/IoTGeneric.puml
!includeurl AWSPuml/InternetOfThings/IoTCore.puml
!includeurl AWSPuml/InternetOfThings/IoTRule.puml
!includeurl AWSPuml/InternetOfThings/IoTShadow.puml
!includeurl AWSPuml/Mobile/APIGateway.puml
!includeurl AWSPuml/General/User.puml
!includeurl AWSPuml/SecurityIdentityAndCompliance/Cognito.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/Database/DynamoDB.puml

APIGatewayParticipant(api, API Gateway, /dispense) order 10
IoTGenericParticipant(dispenser, Dispenser, Id: 123) order 20
IoTShadowParticipant(shadow, Shadow Operations, thingName: 123) order 30
IoTRuleParticipant(rules, Rules Engine, 123/shadow/update/accepted) order 40
LambdaParticipant(app, Dispenser App,) order 50
DynamoDBParticipant(db, Dispenser Table,) order 60
DynamoDBParticipant(log_db, Events Table,) order 70

skinparam noteTextAlignment left

== Request - Dispense operation from App ==
api -> app : GET /dispense?dispenserId=123
app <-> db : Read dispenser record
alt if balance >= $1.00 and no dispense requestId
    app -> db : PUT dispense "requestId": "1234-5678" to request
    app -> shadow: Add to "desired" state
    note right
        {
            "command": "dispense",
            "requestId": "1234-5678",
            "timestamp": 12345
        }    
    end note
    app -> log_db : Dispense: Requested dispenser to activate
    app -> api : 200 - Dispense requested 
else If no credits or request already recorded
    app -> log_db : Dispense: Error, no funds or dispense in operation
    app x-> api : 200 - Insufficient funds or dispense in operation
end
... Some period of time ...
== Response - Dispenser processes the message ==
hnote over dispenser : Dispenser polls for shadow updates (delta or document)
shadow -> dispenser : desired state "request" object (command, requestId, timestamp)
alt timestamp of message > 5 seconds (stale)
    dispenser -> shadow : <i>Optional</i>: reported state "response" object
    note left
        {
            "command": "dispense",
            "requestId": "1234-5678",
            "result": "failure",
            "timestamp": 45678
        }
    end note
    dispenser ->> dispenser : discard message
else timestamp < 5 seconds old (current)
    dispenser -> dispenser : Activate motor for nn milliseconds
    dispenser -> shadow : reported state "response" object
    note left
        {
            "command": "dispense",
            "requestId": "1234-5678",
            "result": "success",
            "timestamp": 45678
        }
    end note
    shadow -> rules: shadow update accepted
    rules -> app : Invoke based on <b>shadow.state.reported.response</b> exists
    app <-> db : Read dispenser record
    alt requestId found in dispenser record
        app -> db : If requestId found, Deduct $1.00 from dispenser 123 credits, clear requestId, update dispenser record
        app -> log_db : Dispense: Operation completed successfully for dispenser
        app -> shadow: Delete desired.request and reported.response objects
    else requestId was <i>NOT</i> found
        app -> log_db : Dispense: ERROR, no corresponding requestId found
        app -> shadow: Delete desired.request and reported.response objects
    end
end
....

In this flow:

* Request - User clicks on "dispense" button in web application
** Lambda is invoked for that request
** Dispenser record read
** If there is a good balance and no in-process requests < 5 seconds old:
*** Record a new request in the dispenser record
*** Publish the *request* object to the dispensers shadow _desired_ state
*** Log a successful request event
*** Return to the API/web app a success message
** If there is _not_ enough credits or a dispense request is still valid (<5 seconds old):
*** Log an error
*** Return to the API/web app a descriptive error

The response operation is decoupled from the request in that the dispenser may be in an offline state. Once online, the response flow continues:

* Dispenser received a shadow update on `$aws/things/shadow/123/delta` or `$aws/things/shadow/123/update/accepted`
** If the timestamp of the request is older than 5 seconds:
*** Add a *response* object to the _reported_ state with a `result=ERROR` indicator (optional - if submitted no credits will be deducted)
*** Discard the message and log locally
** If the request is current (less than 5 seconds old):
*** Activate the motor for set duration
*** _In parallel if possible_, a *response* object to the _reported_ state with the same `requestId`
*** The response message triggers the Rules Engine which looks at the shadow document for a `state.reported.response` objects and if found invokes the Lambda function
*** Lambda determines this is a rules invocation and not API
*** Reads the dispenser record
*** If there is a matching requestId
**** deduct $1.00, clear requestId, update dispenser record
**** Log successful dispenser operations
**** Delete (set to `null`) and request and response objects in the dispensers shadow
*** If no matching dispense requestId was found
**** Log error (should not arrive here)
**** Delete (set to `null`) and request and response objects in the dispensers shadow

The Lambda will also clear out a stale dispense request. There can only be one in-flight dispense request in the dispenser's record.

[NOTE]
A dispenser may get a free pour if it receives the dispense command and then goes offline before publishing the response message.

=== Rules Engine Flows

These flows are subscriptions made by the rules, and the actions they take.

==== Logging Events

The logging rule monitors all messages published to `events` and `events/#`, and invokes a Lambda to persist the events into the DynamoDB *EventsTable*.

.General Event Logging
[plantuml, General Events Logging, svg]
....
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v4.0/dist
!includeurl AWSPuml/AWSCommon.puml

!includeurl AWSPuml/InternetOfThings/IoTCore.puml
!includeurl AWSPuml/InternetOfThings/IoTRule.puml
!includeurl AWSPuml/Compute/Lambda.puml
!includeurl AWSPuml/Database/DynamoDB.puml

IoTCoreParticipant(broker, Message Broker,) order 10
IoTRuleParticipant(rule, Rules Engine,) order 20
LambdaParticipant(logging, Log Events,) order 30
DynamoDBParticipant(db, Events Table,) order 40

== Changes to Shadow trigger rule: LogShadowEvents ==
broker -> rule : Topic: $aws/things/+/shadow/update/documents\nMessage: (JSON)\nshadow document
rule -> logging : Rule: LogShadowEvents\nEvent:\nmessage
== Messages to general event topic trigger rule: LogGenericEvents ==
broker -> rule : Topic: events\nMessage: (JSON)\n{\n  "dispenserId": "nnn"\n  "log": "message to store"\n}
rule -> logging : Rule: LogGenericEvents\nEvent:\nmessage, timestamp() as ts
== Messages to specific event topic trigger rule: LogDispenserEvents ==
broker -> rule : Topic: events/<b>123</b>\nMessage (string):\n"message to store"
rule -> logging : Rule: LogDispenserEvents\nevent:\nmessage, timestamp() as ts, topic() as dispenserId
...
logging -> db : Put entry:\ndispenserId: nnn (or 000 for generic)\nlog: message\ntimestamp: isoformat\n
....

There are three logging rules for the workshop, all which log events to the *EventsTable*. The *LogShadowEvents* rule monitors for shadow update documents, adds the topic which will identify the dispenser, then invokes the *ProcessEvents* Lambda function. Similarly for messages published to the `events` and `events/nnn` (dispenser ID) topics, the *LogGenericEvents* and *LogDispenserEvents* rules process the messages and invoke *ProcessEvents*.

The Lambda function parses the incoming details and creates the formatted entries that then published to the DynamoDB *EventsTable*.

